/**
 * A React key for one lifecycle event.
 *
 * **`event.id` is not safe as a key.** It is not generated by the reducer: each
 * lifecycle operation stores whatever the caller passed as `id`
 * (`SUBMIT_FOR_REVIEW { id, actor, timestamp }`), and the shipped CLI docs show
 * a literal for it. In the live vault a note's two events — written by
 * `powerhouse-agent` and `knowledge-reviewer` — both carry the *document's* id
 * as their event id, so React saw two children with one key and warned that
 * they may be duplicated or omitted.
 *
 * The timeline is append-only and rendered in document order, so position is
 * stable; combining it with the identity the event does carry gives a key that
 * is unique by construction without pretending `id` was ever unique.
 */
export function lifecycleKey(
  event: {
    id?: string | null;
    fromStatus?: string | null;
    toStatus?: string | null;
    timestamp?: string | null;
  },
  index: number,
): string {
  return [
    event.id ?? "",
    event.fromStatus ?? "",
    event.toStatus ?? "",
    event.timestamp ?? "",
    index,
  ].join("|");
}
